export const FETCH_GIT_USERS = "FETCH_GIT_USERS";
export const FETCH_GIT_USERS_SUCCESS = "FETCH_GIT_USERS_SUCCESS";
export const FETCH_GIT_USERS_FAILURE = "FETCH_GIT_USERS_FAILURE";

export const FETCH_SINGLE_USER = "FETCH_SINGLE_USER";
export const FETCH_SINGLE_USER_SUCCESS = "FETCH_SINGLE_USER_SUCCESS";
export const FETCH_SINGLE_USER_FAILURE = "FETCH_SINGLE_USER_FAILURE";

export const FETCH_USER_REPO = "FETCH_USER_REPO";
export const FETCH_USER_REPO_SUCCESS = "FETCH_USER_REPO_SUCCESS";
export const FETCH_USER_REPO_FAILURE = "FETCH_USER_REPO_FAILURE";

export const SEARCH = "SEARCH";
export const SEARCH_SUCCESS = "SEARCH_SUCCESS";
export const SEARCH_FAILURE = "SEARCH_FAILURE";
